IF
  OR(2)
    Global("TSSpawnGuards","AR1000",0)
    Global("TSSpawnGuards","AR1005",0)
THEN
  RESPONSE #100
    DestroySelf()
END

IF
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),8)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    Attack(LastSeenBy(Myself))
END

IF
  See(NearestEnemyOf(Myself))
  !Range(LastSeenBy(Myself),8)
THEN
  RESPONSE #100
    EquipRanged()
    Attack(LastSeenBy(Myself))
END


